### PR TITLE
preserve existing settings

### LINKED ISSUE #24: Allow setting custom TextureImporterPlatformSettings
After dicing and generating the diced texture, it'd be nice to automatically apply custom compression settings.

This would make rebuilding it a lot easier because every time it resets to default.

I saw there is a class called `UnityEditor.TextureImporterPlatformSettings` that seems to hold this information, but I'm not experienced enough in UnityEditor to know how to include it in the `SpriteDicing.Editors.DicedSpriteAtlasEditor` class.

Screen Shot 2022-04-08 at 12 54 36 PM
.

### PR DESCRIPTION
**Pull request by Elringus**
This will preserve texture import settings set for generated atlas textures on consequent rebuilds; closes #24.

### CODE REVIEW

**Comment by rafaelGuerreiro** [comment]
Thank you so much for taking a try at this, I think your idea is better than what I initially thought.

This solution works, but I noticed a couple of behaviors:

1. It copies the settings from the first image, which is nice because it will be applied automatically for newer images when we rebuild.
2. I noticed it doesn't copy platform-specific settings, only default is copied.

**Comment by Elringus** [comment]
> I noticed it doesn't copy platform-specific settings, only default is copied.
Indeed, I wasn't able to find a way to read all the platform-specific settings from an existing asset. Or, more precisely, I'm not sure if there is a way to get a list of the available platforms for [the method](https://docs.unity3d.com/ScriptReference/TextureImporter.GetPlatformTextureSettings.html). In the docs they list some of them, but it doesn't feel right to hard-code the options.

**Comment by rafaelGuerreiro** [comment]
I was able to list all the existing platforms, but I'm not sure this is a good way of doing that. It lists too much.

```
Enum.GetValues(typeof(RuntimePlatform))
  .Cast<RuntimePlatform>()
  .ForEach(platform => Debug.Log(platform.ToString()));
```

**Comment by Elringus** [comment]
Here is how they're doing it internally: https://github.com/Unity-Technologies/UnityCsReference/blob/2020.3/Editor/Mono/ImportSettings/TextureImportPlatformSettings.cs#L163 It is only available in Unity 2020+, though the actual BuildPlatform stuff can be found in 2019.4 as well: https://github.com/Unity-Technologies/UnityCsReference/blob/2019.4/Editor/Mono/BuildPipeline/BuildPlatform.cs#L17

Unfortunately, both APIs are internal. Not sure if it's better to hack-access them with reflection or use `RuntimePlatform` enum as you've suggested (in which case I wonder what's the performance implications would be).

**Comment by Elringus** [comment]
Nevermind, using `RuntimePlatform` won't work anyway, as it doesn't have options like "standalone".

**Comment by Elringus** [comment]
@rafaelGuerreiro I've added preservation of platform-specific settings, please let me know if it's working for you.

**Comment by rafaelGuerreiro** [comment]
Thank you so much for working on this! It's working nicely now.

Would you be able to create a new release with these features?

**Comment by Elringus** [comment]
Sure, will push a new release tomorrow. Thanks for the suggestions and testing!

**Comment by rafaelGuerreiro** [comment]
Sorry for the long delay, I had to take my computer to fix. But now that I'm trying the new version, I discovered a bug. It doesn't work when it's the first time generating the sprite because it can't find one to copy from.

Essentially failing here: `settings.TryImportExisting(TexturesProperty.GetArrayElementAtIndex(0).objectReferenceValue as Texture);`

**Comment by Elringus** [comment]
Fixed in #26, thank you!

**Pull request merged**
