### PR TITLE
Enable animations with transparent frames

### PR DESCRIPTION
**Pull request by rafaelGuerreiro**
When a series of animations contain transparent frames, which is useful for timing and fade in/out techniques, sprite dicing wouldn't allow them to be created because of an exception when calculating min vertices.

The solution is to assume a transparent square of 100 by 100.

Also added a transparent texture for testing.

### CODE REVIEW

**Comment by Elringus** [comment]
Hi, Thanks for the PR! Can you please pull latest changes from the master branch? Something is wrong with the test workflow, maybe it will help.

**Comment by rafaelGuerreiro** [comment]
Ah, sorry, I probably got it messed up because of the Unity version, let me download the correct version and try again.

**Comment by Elringus** [comment]
Looks like something is wrong with Unity activation CI action, sorry. I will try another PR to check if it depends on the author of the commit. Please don't close this one for the time being.

**Comment by Elringus** [comment]
merged via #23

**Pull request closed without merging**
