### PR TITLE
Fix warning message for transparent slices

### PR DESCRIPTION
**Pull request by rguerreiro-kb**
Transparent sprites, when sliced generate this very annoying message from Unity. This PR attempts to fix them by setting the missing metadata.

Screenshot 2023-07-03 at 6 19 30 PM

### CODE REVIEW

**Comment by Elringus** [comment]
Hey, Thanks for the PR! Can you please specify Unity version which generates the warnings (or repro steps)? I'm using 2019.4 and never seen them.

**Comment by rguerreiro-kb** [comment]
Great question! Yes, it also happens on Unity 2019, and above. I've included a Scene with the transparent image that existed before from another PR, and a newly generated one. You can toggle the GameObjects and you'll see the logs showing this warning.

Nothing else happens other than the warning, but it gets in the way of legitimate logs.

`Assets/Samples/Scenes/TransparentTest.unity`

**Comment by Elringus** [comment]
I've checked your scene and pre-generated asset indeed produce warnings, but after re-generating it in 2019.4 (w/o the proposed changes) there are no warnings. I assume you've generated it with a later Unity version? Can you please specify which exactly?

**Comment by rguerreiro-kb** [comment]
Actually, it's because you've regenerated in this branch, which contains the fix. If you regenerate in master, you'll see the warning message again.

**Comment by Elringus** [comment]
I've commented out the changes before testing. Weird. That said, even though I don't have warnings, generated empty sprite looks like this:

419329779969e62b92f953fe1b579d1e

— which is still obviously a bug. It's probably because the mesh retains data from Unity's internal create sprite method. I'll look into this more.

**Comment by rguerreiro-kb** [comment]
Weird, I don't see these artifacts in the image, but I did see something like that when I was coding it initially and I messed up the vertices, uvs, and triangles. I don't remember the combination, though. I'll try to reproduce that.

**Comment by Elringus** [comment]
> Weird, I don't see these artifacts in the image, but I did see something like that when I was coding it initially and I messed up the vertices, uvs, and triangles. I don't remember the combination, though. I'll try to reproduce that.

My bad, when testing I didn't comment out the `if (vertices.Count > 0)` clause (I thought it was there initially). It's now reproducing as you've reported. Sorry for the confusion.

**Comment by rguerreiro-kb** [comment]
Ah, cool. Do you want me to remove the extra scene and all the stuff I added in the last commit? I can regenerate the Flat one that existed before.

**Comment by Elringus** [comment]
It's ok I'll brush it up myself and merge the PR. Thanks again for the contribution!

**Pull request merged**
